### ISSUE TITLE
Bug: Error when generating Befriender Profile Report with no regions

### ISSUE THREAD

**Issue by jasonqiu212** [ShenyiCui/Lions-Rails-6-IssueTicketing#10]
## Issue Description (Unexpected Behaviour)
- Error in generating Befriender Profile Report when no regions are selected.

## Expected Behaviour
- In `master` branch and staging site, when no regions are selected, the report generation works as usual, with all the numbers being 0.

## Steps to Reproduce the Error
1. Go to 'Reports' -> 'Befriender Profile Report'.
2. Click on 'Unselect all regions'.
3. Click on 'Generate report'.

## Screenshots / Others (Additional context)
![Screen Shot 2022-06-14 at 5 13 46 PM](https://user-images.githubusercontent.com/25262042/173543563-b28b356e-64e1-4955-a81d-da17b94700ff.png)

**Comment by Santosh3007** [comment]
https://gitlab.com/nuscvwo/lions/rails/-/commit/fad0ad89e2e31b4598b014dca98b50c5539fa0d3
