### ISSUE TITLE
Bug: Ad-hoc Checkcall filters may not be working correctly

### ISSUE THREAD

**Issue by cheeheng** [ShenyiCui/Lions-Rails-6-IssueTicketing#11]
## Issue Description (Unexpected Behaviour)
Possibly incorrect number of results when searching in ad-hoc checkcall.

## Expected Behaviour
There should be 1 result, assuming the master branch is correct.

## Steps to Reproduce the Error
1. Go to http://localhost:3000/operation/checkcalls/adhoc
2. Search for Zone CS4 and Approval Status Pending
3. On the master branch, I got 1 result, but on the rails-upgrade branch, there is no result.

## Screenshots / Others (Additional context)
Rails Testing branch
![image](https://user-images.githubusercontent.com/13196670/173544069-985a18e2-6b2a-4b1a-903d-bd367373c3c9.png)

Staging
![image](https://user-images.githubusercontent.com/13196670/173556345-2360dc91-0a45-4692-9cc8-e9ca58f1d7d7.png)

**Comment by ekowidianto** [comment]
can show the comparison also? thanks

**Comment by cheeheng** [comment]
I have updated the original post to fulfil @ekowidianto's request.

**Comment by ShenyiCui** [comment]
![Screenshot 2022-06-15 at 2 14 01 PM](https://user-images.githubusercontent.com/29945147/173755465-d1fa2151-116c-41fd-90ee-cf96068694a9.png)

`app/models/cvwo/person.rb:1491`
Discrepancies start to appear here.

**Comment by Santosh3007** [comment]
https://gitlab.com/nuscvwo/lions/rails/-/commit/6fb9b7b3bf355216e9a182dac4487cf71f514fe3

**Comment by ekowidianto** [comment]
Reopen

**Comment by Santosh3007** [comment]
Fixed previous commit
https://gitlab.com/nuscvwo/lions/rails/-/commit/f750306669d6fdd3ab0a5ccd56ef75163ce7de01
