### ISSUE TITLE
Bug: Unable to Update Organisation Information

### ISSUE THREAD

**Issue by chloeelim** [ShenyiCui/Lions-Rails-6-IssueTicketing#14]
## Issue Description (Unexpected Behaviour)
- This issue is probably the same fix to [issue#12](https://github.com/ShenyiCui/Lions-Rails-6-IssueTicketing/issues/12); update_attributes deprecated
- This error does not appear in staging
- When trying to edit (ie: update) an organisation, a NoMethodError is thrown

## Expected Behaviour
- Should be able to update the organisation without throwing any errors

## Steps to Reproduce the Error
1. Go to Administration > Organisation
2. Edit any organisation by clicking the pencil icon
3. Edit some field (eg: Organisation Name)
4. Click Update Organisation
5. A  NoMethodError in Admin::OrganisationsController#update is thrown

## Screenshots / Others (Additional context)
<img width="1208" alt="Screenshot 2022-06-14 at 11 15 21 PM" src="https://user-images.githubusercontent.com/79991214/173623137-2f30dee3-620c-4a11-b948-0daa69c94f7c.png">

- look at lines 150 and 166 of app/controllers/admin/organisations_controller.rb

**Comment by ShenyiCui** [comment]
Resolved via https://gitlab.com/nuscvwo/lions/rails/-/merge_requests/2597/diffs?commit_id=ca3e1d24392883102e57bbe07e776b2856fe9301
