### ISSUE TITLE
Bug(Befriendees): not all cases show up even when the flag is false

### ISSUE THREAD

**Issue by cheeheng** [ShenyiCui/Lions-Rails-6-IssueTicketing#15]
## Issue Description (Unexpected Behaviour)
Not all cases show up when 'Show only active cases' is false. 

## Expected Behaviour
All the 18211 entries should show up (when I tested locally on the master branch) when 'Show only active cases' is set to false. Only 6720 results are returned on the rails-upgrade branch.

## Steps to Reproduce the Error
1. Go to https://staging.cvwo.lb.org.sg/admin/befriendees
2. Set the 'on-off checkbox' of 'Show only active cases' (under Befriendee Listing) to off.

## Screenshots / Others (Additional context)
This is the page I am taking about
![image](https://user-images.githubusercontent.com/13196670/173720627-43b4d7de-b003-4c2a-b986-4642af8c2d2e.png)

**Comment by Santosh3007** [comment]
https://gitlab.com/nuscvwo/lions/rails/-/commit/67618462dc31f03c43a0d1fbb8e0418da7dae68f
