### ISSUE TITLE
Bug(ActivitySummaryReport) - Activities by Sponsors not consistent

### ISSUE THREAD

**Issue by seelengxd** [ShenyiCui/Lions-Rails-6-IssueTicketing#16]
## Issue Description (Unexpected Behaviour)
- This error does not appear in staging.
- When I add a sponsor to an activity, Activities by Sponsors no longer updates consistently.

## Expected Behaviour
Individuals should be 1, No Sponsor Type should be 59

## Steps to Reproduce the Error
1. I was masquerading, but the number should be inconsistent regardless
2. Try to add a individual sponsor like this: https://staging.cvwo.lb.org.sg/operation/activity_sessions/115756
3. Go to Activity Summary Report and look at Activities by Sponsors
4. Click into the number for No Sponsor Type
5. Number should not match

## Screenshots / Others (Additional context)
![Testing](https://user-images.githubusercontent.com/34371483/173728220-36f49583-279a-4c62-8c16-2a6f8480520d.png)

- P.S. this page is going to be a pain to test because of the *ridiculous* load time

**Comment by ShenyiCui** [comment]
![Screenshot 2022-06-16 at 10 57 17 AM](https://user-images.githubusercontent.com/29945147/173981536-2e4cf767-0778-48b6-aaa2-885f8397bfa8.png)
![Screenshot 2022-06-16 at 10 57 25 AM](https://user-images.githubusercontent.com/29945147/173981550-f51db310-e4b1-418b-a354-be663ecf135a.png)

Hmmm, I cannot seem to recreate this error.

**Comment by ShenyiCui** [comment]
Could you try again? Santosh cannot recreate this error either
