### ISSUE TITLE
Bug(Reports/ AAC/ Monthly Statistics Report): MissingAttributeError

### ISSUE THREAD

**Issue by chloeelim** [ShenyiCui/Lions-Rails-6-IssueTicketing#18]
## Issue Description (Unexpected Behaviour)
- This issue does not occur in staging.
- A MissingAttributeError is thrown when clicking on one of the report's non-zero numbers for closed cases

## Expected Behaviour
- The detailed report of closed cases in the selected region should be generated, see screenshot below

## Steps to Reproduce the Error
1. Go to Reports > AAC > Monthly Statistics Report
2. Select report generation by current month (default) (but I think the issue persists regardless of date range)
3. Click on a non-zero number in the 'Closed Cases' row
4. A MissingAttributeError in Reports::SacMonthlyStatsReport#closed_cases will be thrown

## Screenshots / Others (Additional context)
- I also tried testing on master on my local computer and the issue doesn't crop up so I think this shouldn't be an issue with my database

<img width="1198" alt="Screenshot 2022-06-15 at 11 20 56 AM" src="https://user-images.githubusercontent.com/79991214/173730956-d56e37c1-7c24-4679-9c5f-d15629cc2684.png">

Error Thrown:
<img width="1440" alt="Screenshot 2022-06-15 at 11 18 20 AM" src="https://user-images.githubusercontent.com/79991214/173730993-f781990a-34d6-4001-84c2-ed828486d795.png">

Expected output:
<img width="1434" alt="Screenshot 2022-06-15 at 11 20 24 AM" src="https://user-images.githubusercontent.com/79991214/173731167-2849db7d-a41b-4e4b-8dc2-8c47b27d1247.png">

**Comment by ekowidianto** [comment]
Similar to #19
