### ISSUE TITLE
Bug(EPES Report): Error thrown when list of closed cases is requested

### ISSUE THREAD

**Issue by cheeheng** [ShenyiCui/Lions-Rails-6-IssueTicketing#19]
## Issue Description (Unexpected Behaviour)
When the list of closed cases is requested, an error is thrown.

## Expected Behaviour
There should not be such an error.

## Steps to Reproduce the Error
1. Go to http://localhost:3000/reports/epes_report
2. Click on 'Generate Report'
3. Scroll down to the table, and then to the rightmost column, and locate 11.
4. Click on the number 11, it should be a hyperlink.

## Screenshots / Others (Additional context)
![image](https://user-images.githubusercontent.com/13196670/173734124-7ac7f71f-2b12-49a0-bb29-adbcc5786b18.png)

**Comment by ekowidianto** [comment]
Rails 6:
<img width="824" alt="image" src="https://user-images.githubusercontent.com/42570513/173744326-d54e715b-43fb-4636-b682-4f7ae48d1362.png">


Rails 5:
<img width="824" alt="image" src="https://user-images.githubusercontent.com/42570513/173744378-c3a12179-2b24-47f6-8a07-953d5f62ced6.png">

**Comment by ekowidianto** [comment]
prp somehow not fully loaded for the proc

**Comment by cheeheng** [comment]
Similar error shows up in the EPES Half Yearly Report

To reproduce, go to the EPES Half Yearly Report, then click 'Generate Report'. Go to Total Number of Clients row, then click on the hyperlink on the rightmost column.

![image](https://user-images.githubusercontent.com/13196670/173752188-c159da8f-3417-4921-b432-1f96a722de9e.png)

**Comment by cheeheng** [comment]
Similar issue appears in the EPES Performance Tracking Report. Steps to reproduce are the same as in the original bug report, except for the report.

The error:
![image](https://user-images.githubusercontent.com/13196670/173753020-96befa3e-2193-4489-ac14-d78bc3f530f0.png)

**Comment by ShenyiCui** [comment]
temporary fix: add `record.reload`
`app/controllers/concerns/reports/procs.rb:94`
Proc Called From
`app/controllers/reports/generic_client_stats_report_controller.rb:122`

This also fixes #18
