### ISSUE TITLE
Bug: DatePicker doesn't show date options

### ISSUE THREAD

**Issue by ShenyiCui** [ShenyiCui/Lions-Rails-6-IssueTicketing#2]
## Issue Description (Unexpected Behaviour)
- Date Picker input fields on Create New CheckCall do not show the helper date picker options
- Isolated to Commit: `d3654be8a8e8c986ef29a6595bd2a27db014fcce`
- It has something to do with rendering a new column in a button as when its rendered outside of the column it works

## Expected Behaviour
- Input fields should show the date and time picker helper options

## Steps to Reproduce the Error
1. Go to http://localhost:3000/operation/checkcalls/new/group/212

## Screenshots / Others (Additional context)
![Screenshot 2022-06-13 at 4 39 44 PM](https://user-images.githubusercontent.com/29945147/173314370-6cc7953f-3c88-47e2-8907-567fcf2f8de2.png)

## Relevant Files
- app/views/operation/checkcalls/_group_form.html.erb
- app/views/operation/checkcalls/_group_form_column.html.erb

**Comment by cheeheng** [comment]
On the same page, the text in the 'create 1 checkcall' button does not show up.

**Comment by ekowidianto** [comment]
Caused by gem 'simple_form-bootstrap', git: 'https://github.com/raymondtangsc/simple_form-bootstrap' 

In rails 5.2.8 branch, when I switched the gem from joel's to raymond's, the error persists.

See if we can revert to joel's branch and maybe just remove the rails `< 6` version in the gemspec (and run the gem's tests).

**Comment by ShenyiCui** [comment]
Forked off the branch from Joels at [simple_form-bootstrap](https://github.com/ShenyiCui/simple_form-bootstrap). Changed `gemspec` dependency then ran `bundle update`. Everything is working, should I push this fix? Or should I make a repo for this in the CVWO gitlab? @ekowidianto
