### ISSUE TITLE
Bug: Error in displaying Befriendee/Befriender Checkcall Report

### ISSUE THREAD

**Issue by jasonqiu212** [ShenyiCui/Lions-Rails-6-IssueTicketing#20]
## Issue Description (Unexpected Behaviour)
- When clicking into Befriendee Checkcall Report, a duration parsing error pops up.
- Same issue when clicking into Befriender Checkcall Report.

## Expected Behaviour
- On staging and `master` branch, the reports show up normally.

## Steps to Reproduce the Error
1. Go to Reports -> Befriendee Checkcall Report.
2. See error.
3. Go to Reports -> Befriender Checkcall Report.
4. See error.

## Screenshots / Others (Additional context)
![Screen Shot 2022-06-15 at 1 58 41 PM](https://user-images.githubusercontent.com/25262042/173753572-1fb54d36-a22d-4eec-90ed-86e305761391.png)

**Comment by Santosh3007** [comment]
https://gitlab.com/nuscvwo/lions/rails/-/commit/d85fff345a0d5ada8744d21b5724e0352616f282
