### ISSUE TITLE
Bug(CMS): Client Histories no longer deletable

### ISSUE THREAD

**Issue by seelengxd** [ShenyiCui/Lions-Rails-6-IssueTicketing#21]
## Issue Description (Unexpected Behaviour)
- This bug does not appear in master branch.
- Deletion no longer works for case history. 

## Expected Behaviour
- Pressing the Delete Icon should delete accordingly.

## Steps to Reproduce the Error
1. Go to [a case and click on the client tab](http://localhost:8000/v2/cases/81/clients/17/history)
2. Scroll down the to History tab. Click add new history.
3. Try to delete your history with the trash icon.

## Screenshots / Others (Additional context)
![image](https://user-images.githubusercontent.com/34371483/173753565-ae813682-d84d-4b5e-a44c-55b422e5c6aa.png)

**Comment by ekowidianto** [comment]
Seems like theres something wrong with destroying using nested attributes for rails 6.1...

@PeppaPigHS Perhaps a workaround would be to either:
1) Create a separate endpoint to destroy the history (both frontend and backend changes are needed), or
2) Check if a history is to be destroyed in the current update endpoint and invoke the destroy! method on the history record directly (only backend change needed).

**Comment by ekowidianto** [comment]
@PeppaPigHS add a comment as well in the codebase on why its done that way

**Comment by peppapighs** [comment]
https://gitlab.com/nuscvwo/lions/rails/-/commit/27cfac99306073c5899ea413737f73b61448aed5
