### ISSUE TITLE
Bug (Befriending Contact Frequency Report): floating decimal in total values

### ISSUE THREAD

**Issue by cheeheng** [ShenyiCui/Lions-Rails-6-IssueTicketing#22]
## Issue Description (Unexpected Behaviour)
Sorry for nitpicking on such issues, but I found an additional .0 in the bottom-most total row for most of the columns in the Befriending Contact Frequency Report.

## Expected Behaviour
The .0 should not exist. It should have been an integer type instead of a double.

## Steps to Reproduce the Error
1. Go to http://localhost:3000/reports/befriending_contact_frequency_report/
2. Click on 'Generate Report'
3. Scroll down to the bottom, where there are text in bold, representing the subtotal
4. Notice the extra .0 in the output.

## Screenshots / Others (Additional context)
Rails upgrade branch
![image](https://user-images.githubusercontent.com/13196670/173757055-d35674cd-cdab-43fd-b40e-3b116830f715.png)

Staging
![image](https://user-images.githubusercontent.com/13196670/173757152-18aedc7c-24ef-4791-a244-efd443eac2be.png)

**Comment by cheeheng** [comment]
I found a similar issue in the Befriending Home Visit Frequency Report (both report and excel sheet). I am not sure how the type suddenly changed from integer to double.

**Comment by peppapighs** [comment]
https://gitlab.com/nuscvwo/lions/rails/-/commit/3fc39a0b29e2d9bce8896082668d0535d0f0ad2e
