### ISSUE TITLE
Bug(CMS): Deprecation warning when downloading reports

### ISSUE THREAD

**Issue by jasonqiu212** [ShenyiCui/Lions-Rails-6-IssueTicketing#23]
## Issue Description (Unexpected Behaviour)
- Unable to download EPES Half-yearly Report and CS Home Visit Monitoring Report.
- System prompts Deprecation warning.
- CS summary report cannot be downloaded on both staging and localhost -> Most likely not a Rails upgrade issue.

## Expected Behaviour
- For EPES Half-yearly report and CS Home Visit Monitoring report, as per staging, an excel file is downloaded after clicking on 'Download Report'.

## Steps to Reproduce the Error
1. Go to Reports -> EPES Half-yearly Report or CS Home Visit Monitoring Report
2. Click on 'Download Report'

## Screenshots / Others (Additional context)
<img width="888" alt="Screen Shot 2022-06-15 at 4 29 17 PM" src="https://user-images.githubusercontent.com/25262042/173781478-02feb4f9-6b0c-413f-8d91-87abba0add27.png">

**Comment by peppapighs** [comment]
https://gitlab.com/nuscvwo/lions/rails/-/commit/f981ff914f03149337210832307c2f6fd2ff3720
