### ISSUE TITLE
Bug(CMS): CS Home Visit Monitoring Report no longer loads

### ISSUE THREAD

**Issue by seelengxd** [ShenyiCui/Lions-Rails-6-IssueTicketing#24]
## Issue Description (Unexpected Behaviour)
- Issue does not appear in staging.
- 500 internal server error when loading CS Home Visit Monitoring Report
- looks railsy to me from the console error

## Expected Behaviour
- What should've happened instead? What is the correct output? 
- You can `git switch` to the master branch and compare outputs.

## Steps to Reproduce the Error
1. Go to [the report](https://cmsstaging.cvwo.lb.org.sg/v2/reports/home_visit_monitoring_report)
2. See 500 internal server error in networks tab

## Screenshots / Others (Additional context)
Console Error
![image](https://user-images.githubusercontent.com/34371483/173782548-f19fad16-05b8-4530-92a4-c49fd2f704b3.png)

**Comment by ShenyiCui** [comment]
Hi! could you try again? it works on Peps and Santosh's local dev

**Comment by seelengxd** [comment]
somehow it works after resetting the database o_o
