### ISSUE TITLE
Bug(CMS/Intake): Unable to Promote Intake To Case/ Reject Intake

### ISSUE THREAD

**Issue by chloeelim** [ShenyiCui/Lions-Rails-6-IssueTicketing#25]
## Issue Description (Unexpected Behaviour)
- This error cannot be replicated on staging (there's a unrelated frontend bug that screws up intake so you can't get to this stage on staging, we fixed it and you might want to pull from our branch [not pushed yet, i'll update with the name when its ready] to investigate this)
- Anyway, this error does not appear in master (which has the frontend fix)
- When trying to transfer case workers (back to the same person), you will not be able to promote or reject an intake

## Expected Behaviour
- You should be able to promote/ reject the intake (according to the intake assessment)

## Steps to Reproduce the Error
1. Go to Lions CMS > Intakes
2. Click on an intake that is "Pending Intake Worker Assignment"
3. Assign an intake worker to a staff
4. Then, click on "Change Intake Worker"
5. Reassign the intake back to the same staff who was previously unassigned
6. Then, create an intake assessment, set the assessment outcome to either "Approved" or "Rejected"
7. Then, Approve Case Promotion or Approve Intake Closure
8. When trying to submit the intake promotion/ closure form, a 500 error is thrown

## Screenshots / Others (Additional context)
<img width="1051" alt="Screenshot 2022-06-15 at 6 30 01 PM" src="https://user-images.githubusercontent.com/79991214/173806525-3bfd46e3-f219-4427-9033-d3aa61fcbcda.png">

**Comment by ekowidianto** [comment]
Seems like `INCOMINGREFERRAL.level_two_approval_statuses['Approved']` needs to be on the same line

**Comment by ekowidianto** [comment]
To check if the changes in this commit is problematic
https://gitlab.com/nuscvwo/lions/rails/-/merge_requests/2597/diffs?commit_id=704b587de881fb4ace418626678711639515f4b7

Can revert to a 1-liner as I have increased the max line length

**Comment by peppapighs** [comment]
It was my mistake during enum refactoring. I did not declare the constant.

**Comment by PeppaPigHS** [comment]
https://gitlab.com/nuscvwo/lions/rails/-/commit/3fdf4dd6a0c4f3d07add95625a2eaa6416554c9c

**Comment by peppapighs** [comment]
https://gitlab.com/nuscvwo/lions/rails/-/commit/ff41ca4e5f56d2073ec3b0b611d4c47bfd847dc6
