### ISSUE TITLE
Deprecation - to_hash

### ISSUE THREAD

**Issue by ekowidianto** [ShenyiCui/Lions-Rails-6-IssueTicketing#26]
Remove deprecated ActiveRecord::Result#to_hash method.

**Comment by ShenyiCui** [comment]
`app/controllers/operation/alerts_controller.rb:203`'s `#to_hash` is not being called on active record. The type is 'Hash'.
![Screenshot 2022-06-16 at 4 54 54 PM](https://user-images.githubusercontent.com/29945147/174032919-dd705b13-a1dc-482b-a3d0-f08342d20e53.png)

**Comment by ekowidianto** [comment]
Noted! thanks for checking
