### ISSUE TITLE
Bug: Deprecated HPC Receipts

### ISSUE THREAD

**Issue by peppapighs** [ShenyiCui/Lions-Rails-6-IssueTicketing#3]
## Issue Description
- When viewing HPC receipt file, Rails throws a deprecation warning error

## Expected Behaviour
- Should successfully generate a receipt.pdf

## Steps to Reproduce the Error
1. Go to HPC > Receipts
2. Click on Search icon button on any receipt in the table
3. Click on 'VIEW RECEIPT FILE' button

## Screenshots / Others (Additional context)
![image](https://user-images.githubusercontent.com/41262596/173509024-da9d7873-1c55-41cb-b432-6357bddc628b.png)

The same error is shown when trying to mail the receipt to the client as it cannot properly generate the receipt file to be mailed.

**Comment by Santosh3007** [comment]
https://gitlab.com/nuscvwo/lions/rails/-/commit/6b0f82d5576a8256dc627c32c41951767f0b2566
