### ISSUE TITLE
Bug: Buttons for adding a Checkcall and mood indicators are not functional

### ISSUE THREAD

**Issue by seelengxd** [ShenyiCui/Lions-Rails-6-IssueTicketing#6]
## Issue Description (Unexpected Behaviour)
- This error does not appear in staging.
- Adding a checkcall for matching groups is problematic as mood indicators are not selectable 

## Expected Behaviour
- Emojis should be clickable [1]
- Button should have text [2]
- Refer to Staging on the right

## Steps to Reproduce the Error
1. Go to 'Befriending Checkcall'
2. Click on 'Add' in one of the matching groups
3. Scroll down to see the green button and click on the emojis you see along the way

## Screenshots / Others (Additional context)
![Untitled 22](https://user-images.githubusercontent.com/34371483/173518819-760e3b78-e502-4dbb-a4c4-e673516a79a5.png)

**Comment by cheeheng** [comment]
There is an additional issue part 3: the 'All attended' status checkbox does not correctly reflect whether all staff have attended. When I click on the 'All attended' status checkbox, the CVWO admin attendance checkbox remains unchecked, but the admin attendance checkbox should be checked.

Similar issue also occurs on Befriendees (set all).

**Comment by cheeheng** [comment]
Part 4: The form submits even though no befriendees are visited. In the master branch, when I attempted to submit the same form, it says that "Checkcall 1 must have at least one befriendee visited or not in".

**Comment by ekowidianto** [comment]
Most likely another jquery/javascript issue.. might be related to https://github.com/ShenyiCui/Lions-Rails-6-IssueTicketing/issues/2

**Comment by ekowidianto** [comment]
Confirmed same issue as #2 
Solution posted in that issue.

**Comment by ShenyiCui** [comment]
Addressed and potential fix addressed in #2
