### ISSUE TITLE
Bug: Registration Date data discrepancy in Befriender Contacts Report

### ISSUE THREAD

**Issue by jasonqiu212** [ShenyiCui/Lions-Rails-6-IssueTicketing#8]
## Issue Description (Unexpected Behaviour)
- Some registration dates are off by 1 day in Befriender Contacts Report.

## Expected Behaviour
- For instance, after doing the below steps, S/N 14 has a registration date of 10/03/2010 in staging and `master` branch.
- But, for `rails-upgrade` branch, S/N 14 has a registration date of 11/03/2010.

## Steps to Reproduce the Error
1. Go to 'Reports' -> 'Befriender Contacts Report'.
2. Click on 'Generate Report' (Query: Jun 1 2022 - Jun 30 2022, Region CS1)
3. Scroll to S/N 14-20.

## Screenshots / Others (Additional context)
Localhost:
![local](https://user-images.githubusercontent.com/25262042/173534434-b9ec1b7f-be5d-4faa-9c36-033f4caa22b7.png)

Staging/`master`:
![stage](https://user-images.githubusercontent.com/25262042/173534442-8a266fc1-8dd8-4565-8f96-6232d9f96d86.png)

**Comment by ekowidianto** [comment]
Check UTC

**Comment by Santosh3007** [comment]
Checked actual entries in database and confirmed that the dates displayed in the testing branch is the correct dates and the dates previously displayed in master and staging are wrong and is in UTC not local time
(Dates in database are in UTC)
![image](https://user-images.githubusercontent.com/34889879/173726811-ef4f0d12-020e-46cf-9c68-d51bf0f9aa13.png)
![image](https://user-images.githubusercontent.com/34889879/173726971-977b38d9-77c8-40e0-9cf4-3cdbef7ab5ef.png)
