### ISSUE TITLE
Bug(AAC/Home-Visit): Filtering by Advance Search Fields Throws Error

### ISSUE THREAD

**Issue by chloeelim** [ShenyiCui/Lions-Rails-6-IssueTicketing#9]
## Issue Description (Unexpected Behaviour)
- This error does not appear on staging
-  Filtering the AAC Home Visit Record by Classification (CBE/ CBF/ both) causes an 500 error, occurs both when masquerading and not
- The same error will occur when filtering for the fields: Flat type, Gender, Race, Religion, Marital status, Nationality, Identity document type, Classification, Centre, Centre Member, Under Service Boundary, Salutation, Mobility Status

## Expected Behaviour
- Should filter all records by the selected filters, see screenshots attached below

## Steps to Reproduce the Error
1. Go to AAC > Home Visit
2. Filter "Classification" either by "CBE"/ "CBF" (or both)
3. You'll notice that the page gets stuck on "Processing"
4. Open up your console and you should notice a 500 error being thrown
5. Alternatively, you can check this link out: http://localhost:3000/centre/home_visit_records?draw=5&columns[0][name]=&columns[1][name]=&columns[2][name]=&columns[3][name]=&columns[4][name]=&columns[5][name]=&columns[6][name]=&columns[7][name]=&columns[8][name]=&columns[9][name]=&columns[10][name]=&columns[11][name]=&columns[12][name]=&columns[13][name]=&columns[14][name]=&columns[15][name]=&columns[16][name]=&columns[17][name]=&columns[18][name]=&columns[19][name]=&columns[20][name]=&order[0][column]=1&order[0][dir]=desc&start=0&length=250&search[value]=&search[regex]=false&flat_type=&gender=&race=&religion=&marital_status=&nationality=&identity_document_type=&classification[]=1047&classification[]=1049&centre_id=&salutation=&mobility_status=&_=1655196084298

[same steps to reproduce for Flat type, Gender, Race, Religion, Marital status, Nationality, Identity document type, Classification, Centre, Centre Member, Under Service Boundary, Salutation, Mobility Status filtering error]

## Screenshots / Others (Additional context)
The fields that aren't working:
<img width="1157" alt="Screenshot 2022-06-14 at 5 22 43 PM" src="https://user-images.githubusercontent.com/79991214/173544019-fad0024d-bd8e-4859-9040-90858cb9ac3d.png">

Error on local host:
<img width="1134" alt="Screenshot 2022-06-14 at 4 41 46 PM" src="https://user-images.githubusercontent.com/79991214/173540031-0d91bc28-291a-47da-b7bd-3d07a8b28876.png">

Expected behaviour on staging:
<img width="1165" alt="Screenshot 2022-06-14 at 5 06 43 PM" src="https://user-images.githubusercontent.com/79991214/173539754-fc53b2bb-f37e-41c3-b402-30dd5c2d396b.png">

Useful? information:
<img width="1137" alt="Screenshot 2022-06-14 at 5 10 37 PM" src="https://user-images.githubusercontent.com/79991214/173540293-f3e670ee-c4e7-47f1-9d79-5593b8483a2a.png">

(from console):
<img width="551" alt="Screenshot 2022-06-14 at 4 36 51 PM" src="https://user-images.githubusercontent.com/79991214/173540344-1f6f0211-f807-426f-a51c-e02518a2893d.png">

(terminal message):
<img width="1427" alt="Screenshot 2022-06-14 at 4 37 56 PM" src="https://user-images.githubusercontent.com/79991214/173540844-50881438-3466-4355-9889-2c250c7d0f16.png">

Also, trying to export excel when filtering by one of these buggy classification will throw the following error (but it's probably should be linked with the filtering issue, so I'm putting this issue here as a sub-problem/consequence):

<img width="1150" alt="Screenshot 2022-06-14 at 5 28 27 PM" src="https://user-images.githubusercontent.com/79991214/173545003-107be9ee-16ea-4c26-ad05-c30805582514.png">

**Comment by ekowidianto** [comment]
visitors model is a polymorphic association, as a result, you need to change `includes` to `preload`

**Comment by ShenyiCui** [comment]
https://gitlab.com/nuscvwo/lions/rails/-/commit/0cc96caf8bf15f2ebae6c90635d6d110572c2e0e
